project:
  type: website
  output-dir: docs

website:
  title: "Welcome to my webpage"
  navbar: 
    left:
      - text: "Menu"
        menu:
          - href: index.qmd
            text: Introduction
          - about.qmd
      - href: index.qmd
        text: Introduction
      - href: about.qmd
        text: Data Story
      - href: Shiny.qmd
        text: Draft
        
    
      

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

